# Generated by Django 2.1.5 on 2019-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default='ABC', max_length=100),
        ),
    ]
