# Generated by Django 2.1.5 on 2019-03-31 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0003_auto_20190331_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('5610ca37-0088-49c5-832e-cab3debf3c6d'), max_length=100),
        ),
    ]
