# Generated by Django 2.1.5 on 2019-03-31 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0004_auto_20190331_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('c3132c80-bd5c-436d-84b1-c13cd77b4028'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('2f2d9f69-bcb8-4d4e-97b5-cb70ce3f3821'), max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
