# Generated by Django 2.1.5 on 2019-03-31 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0005_auto_20190331_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('b9f1568c-fbfe-48a7-967b-f8ea0e92e07e'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('ff76aa89-3f50-4f6c-bf5c-a55a5009f8d4'), max_length=100),
        ),
    ]
