# Generated by Django 2.1.5 on 2019-03-31 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0006_auto_20190331_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('a895103c-9167-45ce-825b-a3707ba09cb8'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('a0994f25-ed2d-47e5-a749-3ab4d9cd8631'), max_length=100),
        ),
    ]
