# Generated by Django 2.1.5 on 2019-04-04 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0007_auto_20190331_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('869f509a-730c-4cfa-aa2b-f5a7b14317d3'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('d9a613eb-d88c-4db9-8afd-cbe8601f6a88'), max_length=100),
        ),
    ]
