# Generated by Django 3.2.5 on 2022-03-22 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SBlokz', '0008_auto_20190404_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('8461967e-2e24-4d09-a2f4-baa1c8758ce6'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_id',
            field=models.CharField(default=uuid.UUID('0415447d-d563-4fb3-b64f-b9964ef09f74'), max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
